src/main/resources/Messages.properties
=> IBP-2046  avg function implementation

src/main/webapp/WEB-INF/static/js/trialmanager/trial-data-manager.js
=> Add validation when TF is added and label is not selected

pom.xml, src/main/java/com/efficio/etl/web/ImportObservationsController.java, src/main/resources/Messages.properties, src/main/webapp/WEB-INF/pages/TrialManager/createTrial.html, src/main/webapp/WEB-INF/pages/importObservations/variateGroupImportMapHeaders.html, src/main/webapp/WEB-INF/static/angular-templates/importObservations/importMappingGroup.html, src/main/webapp/WEB-INF/static/js/importObservations/variate-group-importer-main.js, src/main/webapp/WEB-INF/static/js/importObservations/variateGroupImporter.js, src/main/webapp/WEB-INF/static/js/trialmanager/datasetService.js, src/main/webapp/WEB-INF/static/js/trialmanager/importStudy.js, src/main/webapp/WEB-INF/static/js/trialmanager/manageTrial.js
=> Ibp 2999 add variables when import

src/main/webapp/WEB-INF/static/js/angular-tests/trialmanager/location.spec.js, src/main/webapp/WEB-INF/static/js/trialmanager/environments.js, src/main/webapp/karma.conf.js
Add checking if data sent is null
=> IBP-3058 Check If Data sent is null

src/main/java/com/efficio/fieldbook/service/FieldbookServiceImpl.java, src/main/java/com/efficio/fieldbook/web/trial/controller/BaseTrialController.java, src/test/java/com/efficio/fieldbook/service/FieldbookServiceTest.java, src/test/java/com/efficio/fieldbook/utils/test/LabelPrintingDataUtil.java, src/test/java/com/efficio/fieldbook/web/trial/controller/CreateTrialControllerTest.java
Set operation pair name variable's operation same to id variable
=> IBP-3139 Set Pair Name Variable's Operation 

src/main/webapp/WEB-INF/static/js/angular-tests/trialmanager/experimentalDesign.spec.js
=> IBP-3095 Added unit tests for Front end changes

src/main/java/com/efficio/etl/service/ETLService.java, src/main/java/com/efficio/etl/service/impl/ETLServiceImpl.java, src/main/java/com/efficio/etl/web/ImportObservationsController.java, src/main/java/com/efficio/etl/web/controller/angular/AngularMapOntologyController.java, src/main/java/com/efficio/fieldbook/web/trial/controller/BaseTrialController.java, src/main/java/com/efficio/fieldbook/web/trial/controller/OpenTrialController.java, src/main/webapp/WEB-INF/pages/TrialManager/templates/experimentalDesign.html, src/main/webapp/WEB-INF/static/js/trialmanager/experimentalDesign.js, src/test/java/com/efficio/fieldbook/web/trial/controller/OpenTrialControllerTest.java
=> IBP-3145 expt design mapping

src/main/java/com/efficio/etl/service/ETLService.java, src/main/java/com/efficio/etl/service/impl/ETLServiceImpl.java, src/main/java/com/efficio/etl/web/bean/VariableDTO.java, src/main/java/com/efficio/etl/web/controller/angular/AngularMapOntologyController.java, src/main/java/com/efficio/fieldbook/web/trial/controller/OpenTrialController.java, src/test/java/com/efficio/etl/service/ETLServiceTest.java, src/test/java/com/efficio/etl/web/controller/angular/AngularMapOntologyControllerTest.java, src/test/java/com/efficio/fieldbook/web/trial/controller/OpenTrialControllerTest.java
=> IBP-3292 unit tests for 3145 and3203

src/main/java/com/efficio/etl/web/ImportObservationsController.java, src/test/java/com/efficio/etl/web/ImportObservationsControllerTest.java
=> IBP-3302 Inlcude variates in checking for missing variable headers.

src/main/java/com/efficio/etl/service/impl/ETLServiceImpl.java, src/main/webapp/WEB-INF/pages/etl/angular/angularMapHeaders.html, src/main/webapp/WEB-INF/static/js/design-import/design-import-main.js, src/main/webapp/WEB-INF/static/js/importObservations/variateGroupImporter.js, src/test/java/com/efficio/etl/service/ETLServiceTest.java
=> IBP-3315 fix empty string alias issue

src/main/java/com/efficio/fieldbook/web/common/controller/GermplasmListController.java, src/main/java/com/efficio/fieldbook/web/util/CrossesListUtil.java, src/main/webapp/WEB-INF/pages/Common/includes/openCrossesListModal.html, src/main/webapp/WEB-INF/static/js/fbk-data-table/fieldbook-datatable.js, src/test/java/com/efficio/fieldbook/web/common/controller/CrossingSettingsControllerTest.java, src/test/java/com/efficio/fieldbook/web/util/CrossesListUtilTest.java
Hi @clarysabel and @nahuel-soldevilla.
In this PR I made minors changes to solver the problem when the user changes the labels in system labels.
Please Review
Regards, Diego
=> IBP-3267 review crosses not working changing system labels

pom.xml
https://github.com/IntegratedBreedingPlatform/InventoryManager/pull/6
=> IBP-3255 Upgrade node.js version

src/main/resources/Messages.properties, src/main/webapp/WEB-INF/pages/TrialManager/reviewTrialDetails.html
Add front end display for percentage replication and number of blocks 
IBP-3283-ShowExpDesignParam
=> IBP-3283 Show Experimental Design Parameters 

src/main/java/com/efficio/fieldbook/web/common/service/impl/CrossingTemplateParser.java, src/test/java/com/efficio/fieldbook/web/common/service/impl/CrossingTemplateParserTest.java
=> IBP-2909 - Import Crosses Optimization

src/main/webapp/WEB-INF/static/js/angular/fieldbook-utils.js
Exclude instances with cannot be deleted instances from selection.
=> IBP-3258 Exclude Instance Cannot Be Deleted 

src/main/webapp/WEB-INF/pages/StudyManager/savedFinalList.html
Hide Actions Button if the list is empty.
=>  IBP-3090 FixedErrorOnEmptyCrossesList

src/main/webapp/WEB-INF/pages/Common/includes/exportStudy.html, src/main/webapp/WEB-INF/static/js/fieldbook-common.js
Fix datasets endpoint: add programs/{programId} in url
=> IBP-3513 Add ProgramId In Datasets Endpoint

src/main/java/com/efficio/fieldbook/web/util/DuplicatesUtil.java
Hi @clarysabel and @nahuel-soldevilla 
In this PR I made changes into the validation when the Male Plot has more than 1 Plot.
Please, Review
Regards, Diego
=> IBP-2971 plot reciprocal and pedigree reciprocal are being identified by the system for polycrosses

src/main/java/com/efficio/fieldbook/web/trial/controller/OpenTrialController.java, src/test/java/com/efficio/fieldbook/web/trial/controller/OpenTrialControllerTest.java
Count actual germplasm check size. 
Modify unit test to use fieldbookService.getGermplasmListChecksSize
=> IBP-3420-CountGermplasmChecksSize

src/main/webapp/WEB-INF/static/js/trialmanager/environments.js
=> Fix validation of number of instances.

src/main/webapp/WEB-INF/pages/LabelPrinting/specifyLabelDetails.html
=> IBP-3832 Fix issue with exporting labels. trial.environmentId should be triaLinstanceId

src/main/webapp/WEB-INF/pages/Common/includes/exportTrialInstance.html
Update exportTrialInstance.html to use instanceId (before environmentId)
=> IBP-3825-UseInstanceIdVariable

src/main/webapp/WEB-INF/static/js/angular-tests/trialmanager/studySettings.spec.js, src/main/webapp/WEB-INF/static/js/angular/fieldbook-utils.js
Prepend studyStateService.updateOccured in changefunction of directive showSettingFormElement
Create unit test when updateOccured was called (mock directive element changefunction)
=> IBP-3251-DetectUnsavedChanges

src/main/java/com/efficio/etl/web/controller/angular/AngularMapOntologyController.java, src/main/resources/Messages.properties, src/main/webapp/WEB-INF/static/js/trialmanager/germplasm.js, src/test/java/com/efficio/etl/web/controller/angular/AngularMapOntologyControllerTest.java
=> IBP-3049 variable validation for means dataset import

src/main/webapp/WEB-INF/pages/Common/includes/exportStudy.html, src/main/webapp/WEB-INF/pages/TrialManager/reviewTrialDetails.html, src/main/webapp/WEB-INF/static/js/fieldbook-common.js
Modal for confirmation message 
Scripts for checking if hasFieldMap
=> IBP-3071-ConfirmMessageSerpentineOrderNoFieldMap

src/main/java/com/efficio/fieldbook/web/trial/bean/Instance.java, src/main/java/com/efficio/fieldbook/web/trial/controller/BaseTrialController.java, src/main/java/com/efficio/fieldbook/web/util/WorkbookUtil.java, src/test/java/com/efficio/fieldbook/web/util/WorkbookUtilTest.java
Create experimentId property in instance
=> IBP-3857-SetInstanceExperimentId

src/main/webapp/WEB-INF/pages/TrialManager/templates/trialSettings.html, src/main/webapp/WEB-INF/static/js/angular/fieldbook-utils.js, src/main/webapp/WEB-INF/static/js/trialmanager/trialSettings.js
=> IBP-3852 cant create study with treatment factors

src/main/java/com/efficio/fieldbook/web/trial/controller/OpenTrialController.java, src/test/java/com/efficio/fieldbook/web/trial/controller/OpenTrialControllerTest.java
=> IBP-3902 Set Non Study Variable to null

src/main/java/com/efficio/fieldbook/web/trial/bean/Instance.java, src/main/java/com/efficio/fieldbook/web/trial/controller/BaseTrialController.java, src/main/java/com/efficio/fieldbook/web/util/WorkbookUtil.java, src/main/webapp/WEB-INF/static/js/trialmanager/environments.js, src/test/java/com/efficio/fieldbook/web/util/WorkbookUtilTest.java
Merge branch with IBP-3857-SetInstanceExperimentId
Main changes: environment.js setting instance.experimentId when creating new environment/location
=> IBP-3863-SetInstanceExperimentId

src/main/webapp/WEB-INF/pages/TrialManager/templates/subobservations/subObservationSet.html, src/main/webapp/WEB-INF/pages/TrialManager/templates/subobservations/subObservationTab.html, src/main/webapp/WEB-INF/static/css/fieldbook.css, src/main/webapp/WEB-INF/static/js/trialmanager/subobservations/subObservationTab.js
Move help link icon to header of observation/sub observation
=> IBP-3701-IBP-3724-HelpLinks

src/main/java/com/efficio/etl/service/impl/ETLServiceImpl.java, src/test/java/com/efficio/etl/service/ETLServiceTest.java
Exclude means variable if uploading plot data
=> IBP-3862-ExcludeMeansVariable

src/main/java/com/efficio/fieldbook/web/study/germplasm/StudyGermplasmTransformer.java
=> IBP-4068 Added null check for entry type value

src/main/java/com/efficio/etl/web/controller/angular/AngularMapOntologyController.java, src/main/resources/Messages.properties, src/test/java/com/efficio/etl/web/controller/angular/AngularMapOntologyControllerTest.java
Created logic for checking trial instance value 
Uses reusable util. validateVariableValues to check if trial instance has numeric value
=> IBP-3528-ValidateTrialInstanceValue

src/main/java/com/efficio/fieldbook/web/common/service/impl/ExportStudyEntriesServiceImpl.java, src/main/java/com/efficio/fieldbook/web/importdesign/generator/DesignImportMeasurementRowGenerator.java, src/main/java/com/efficio/fieldbook/web/study/germplasm/StudyEntryTransformer.java, src/main/java/com/efficio/fieldbook/web/util/WorkbookUtil.java, src/test/java/com/efficio/fieldbook/web/common/service/impl/CrossingTemplateExcelExporterTest.java, src/test/java/com/efficio/fieldbook/web/common/service/impl/ExportStudyEntriesServiceTest.java, src/test/java/com/efficio/fieldbook/web/importdesign/generator/DesignImportMeasurementRowGeneratorTest.java, src/test/java/com/efficio/fieldbook/web/util/WorkbookUtilTest.java
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/378
https://github.com/IntegratedBreedingPlatform/Middleware/pull/911
https://github.com/IntegratedBreedingPlatform/Commons/pull/284
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/416
Please, review
Regards, Diego
=> IBP-4058 Remove StockID variable from the ontology

src/main/webapp/WEB-INF/static/js/trialmanager/subobservations/subObservationSet.js
Please review.
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/921
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/429
Regards, Diego
=> IBP-4149 add stock id from plating preparation in observation tab

src/main/webapp/WEB-INF/static/js/trialmanager/germplasm-study-source/germplasmStudySource.js, src/main/webapp/WEB-INF/static/js/trialmanager/germplasm/germplasm.js, src/main/webapp/WEB-INF/static/js/trialmanager/inventory/inventory-tab.js, src/main/webapp/WEB-INF/static/js/trialmanager/manageTrial.js, src/main/webapp/WEB-INF/static/js/trialmanager/subobservations/subObservationSet.js
Please, review
Include:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/438
https://github.com/IntegratedBreedingPlatform/Middleware/pull/938
Regards, Diego
=> IBP-4061 delete classes created to be used in datatable js

src/main/java/com/efficio/fieldbook/web/trial/controller/OpenTrialController.java, src/main/resources/Messages.properties, src/main/webapp/WEB-INF/pages/TrialManager/createTrial.html, src/main/webapp/WEB-INF/static/js/trialmanager/experimentalDesign.js, src/main/webapp/WEB-INF/static/js/trialmanager/manageTrial.js, src/main/webapp/WEB-INF/static/js/trialmanager/studyStateService.js, src/test/java/com/efficio/fieldbook/web/trial/controller/OpenTrialControllerTest.java
Disable delete generated design if study has meansdataset
=> IBP-3233-SetCanBeDeletedFalseIfHasMeansDataset

src/main/webapp/WEB-INF/static/js/trialmanager/germplasm-study-source/germplasm-study-source-tab.html, src/main/webapp/WEB-INF/static/js/trialmanager/germplasm-study-source/germplasmStudySource.js, src/main/webapp/WEB-INF/static/js/trialmanager/germplasm-study-source/germplasmStudySourceService.js, src/main/webapp/WEB-INF/static/js/trialmanager/subobservations/subObservationSet.js
Added Select All Pages Checkbox 
When select All pages clicked, query all germplasm study resource to fetch all gids 
Use _iRecordsTotal when fetching total records to display
=> IBP-4003-SelectAllPages

src/main/java/com/efficio/fieldbook/web/common/controller/CrossingSettingsController.java, src/main/resources/Messages.properties, src/main/webapp/WEB-INF/pages/Common/includes/crossingImportPresets.html, src/main/webapp/WEB-INF/pages/Common/includes/globals.html, src/main/webapp/WEB-INF/static/js/import-crosses.js, src/main/webapp/WEB-INF/static/js/locations.js
For design new crosses the haverst location now is requiered and it is selected by default of the first enviroment of the study.
Please review.
=> IBP-3883 define location from first enviroment as default harvest location

src/main/webapp/WEB-INF/pages/TrialManager/createTrial.html
=> IBP-4158 Extend "Design and planning options" length

src/main/java/com/efficio/fieldbook/web/naming/impl/NamingConventionServiceImpl.java
=> IBP-4160 Something went wrong when I save a harvest list and some entries were removed from Review Advance lines popup

src/main/java/com/efficio/fieldbook/web/naming/impl/NamingConventionServiceImpl.java
Reverts IntegratedBreedingPlatform/Fieldbook#964
=> Revert "IBP-4160 Something went wrong when I save a harvest list and some entries were removed from Review Advance lines popup"

src/main/java/com/efficio/fieldbook/service/FieldbookServiceImpl.java, src/main/java/com/efficio/fieldbook/web/common/service/impl/ExportStudyEntriesServiceImpl.java, src/main/java/com/efficio/fieldbook/web/naming/impl/AdvancingSourceListFactory.java, src/main/java/com/efficio/fieldbook/web/study/germplasm/StudyEntryTransformer.java, src/test/java/com/efficio/etl/service/ETLServiceTest.java, src/test/java/com/efficio/fieldbook/web/common/controller/ExportStudyEntriesControllerTest.java, src/test/java/com/efficio/fieldbook/web/common/service/impl/ExportStudyEntriesServiceTest.java, src/test/java/com/efficio/fieldbook/web/util/KsuFieldbookUtilTest.java
=> IBP-4128 remove id 8255 uplicated in term id enum

src/main/java/com/efficio/fieldbook/service/FieldbookServiceImpl.java, src/test/java/com/efficio/fieldbook/web/trial/controller/SettingsControllerTest.java
=> renamed location.uniqueID by location.programUUID

src/main/webapp/WEB-INF/static/js/trialmanager/observations/change-plot-entry-modal.js
Please review.
Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/461
https://github.com/IntegratedBreedingPlatform/Middleware/pull/961
Regards, Diego
=> IBP-4212 Adding method to count the filtered study entries

src/main/java/com/efficio/etl/service/impl/ETLServiceImpl.java, src/test/java/com/efficio/etl/service/ETLServiceTest.java
Allow user to upload succeeding file w/o ENTRY_TYPE 
cc : @darla-leafnode
=> IBP-4255-AddEntryTypeSucceedingImport

src/main/java/com/efficio/fieldbook/web/common/controller/ExportStudyEntriesController.java, src/main/java/com/efficio/fieldbook/web/fieldmap/controller/GenerateFieldmapController.java, src/test/java/com/efficio/fieldbook/web/common/controller/ExportStudyEntriesControllerTest.java, src/test/java/com/efficio/fieldbook/web/fieldmap/controller/GenerateFieldmapControllerTest.java
Export study entries and field map 
Unit test
=> IBP-4198-ExportFileName

src/main/java/com/efficio/fieldbook/web/common/controller/CrossingSettingsController.java, src/test/java/com/efficio/fieldbook/web/common/controller/CrossingSettingsControllerTest.java
Implement breedingmethod service parameters
IBP-4252-BrapiBreedingMethods
=> IBP-4252-BrapiBreedingMethods

src/main/webapp/WEB-INF/static/js/trialmanager/environments.js
=> IBP-4337 Fix the display of dropdown values for categorical variables in Environment Settings

src/main/java/com/efficio/fieldbook/web/common/controller/ExportStudyEntriesController.java, src/main/java/com/efficio/fieldbook/web/common/service/impl/CrossingTemplateExcelExporter.java, src/main/java/com/efficio/fieldbook/web/fieldmap/controller/GenerateFieldmapController.java
Implement FileNameGenerator.generateFilename new parameters: if null for extension limit is 250 and no extension filename will be returned
=> IBP-4339-ValidateFilenameGenerator

src/test/java/com/efficio/fieldbook/web/common/controller/ExportStudyEntriesControllerTest.java
Revised unit test 
ExportStudyEntriesControllerTest. testExportGermplasmListCSVForStudy
=> IBP-2634-FixFailingUnitTests

src/main/webapp/WEB-INF/static/angular-templates/experimentalDesignPartials/pRepParams.html
Update prep design parameter's tooltip
=> IBP-3352-PrepParamsToolTip

src/main/webapp/WEB-INF/static/js/trialmanager/selectEnvironmentModal.js
Set noOfReplication value to zero if PREP DESIGN, else use noOfReplication
=> IBP-4515-AdvanceStudyIfPrepZeroNoOfReplication

src/main/webapp/WEB-INF/static/js/fieldbook-common.js, src/main/webapp/WEB-INF/static/js/trialmanager/manageTrial.js
=> IBP-4669 Fix the loading of Label Printing page

src/main/java/com/efficio/fieldbook/web/trial/controller/AdvancingController.java, src/test/java/com/efficio/fieldbook/web/trial/controller/AdvancingControllerTest.java
When delete entries, update advance sources' selected plant count 
Modify existing unit test
=> IBP-4160-UpdateSelectedPlantWhenEntriesDeleted

src/main/resources/fieldbook.properties, src/main/webapp/WEB-INF/Fieldbook-servlet.xml
Value should be from bmsconfig > fieldbook.properties
=> IBP-4644-MaxUploadSize

pom.xml
=> IBP-4681 Upgrade Node version to 14.17

src/main/webapp/WEB-INF/Fieldbook-servlet.xml
This reverts commit 1b139a1cce647ca0a88dd65d41e1e6e433eb69a7.
=> IBP-4607 Revert "Added germplasmNameTypeService bean to fieldbook."

src/main/webapp/WEB-INF/Fieldbook-servlet.xml
Please, review
Include:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/545
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1089
https://github.com/IntegratedBreedingPlatform/Workbench/pull/514
=> IBP-4607 Get all name types and Create a new one.

src/main/webapp/WEB-INF/static/js/trialmanager/germplasm-study-source/germplasmStudySource.js, src/main/webapp/WEB-INF/static/js/trialmanager/germplasm-study-source/germplasmStudySourceService.js, src/main/webapp/WEB-INF/static/js/trialmanager/inventory/lot-creation/lot-creation-modal.html, src/main/webapp/WEB-INF/static/js/trialmanager/inventory/lot-creation/lot-creation-modal.js
Please, review
Include:
IntegratedBreedingPlatform/Middleware#991
IntegratedBreedingPlatform/Workbench#434
IntegratedBreedingPlatform/BMSAPI#548
=> IBP-4209 create inventory lot in search germplasm

src/main/webapp/WEB-INF/static/js/trialmanager/file/file.service.js, src/main/webapp/WEB-INF/static/js/trialmanager/subobservations/subObservationSet.js
=> IBP-4732 ksu fieldbook image integration

src/main/webapp/WEB-INF/static/angular-templates/subObservations/observationInlineEditor.html, src/main/webapp/WEB-INF/static/css/fieldbook.css, src/main/webapp/WEB-INF/static/js/angular-tests/trialmanager/subObservationSet.spec.js, src/main/webapp/WEB-INF/static/js/trialmanager/experimentalDesign.js, src/main/webapp/WEB-INF/static/js/trialmanager/file/file.service.js, src/main/webapp/WEB-INF/static/js/trialmanager/manageTrial.js, src/main/webapp/WEB-INF/static/js/trialmanager/subobservations/subObservationSet.js
- file upload ux improvements, move file upload to file manager
=> IBP-4815 file upload improvements

src/test/java/com/efficio/fieldbook/web/trial/controller/AdvancingControllerTest.java
Please, review
Included:
IntegratedBreedingPlatform/Middleware#1117
IntegratedBreedingPlatform/Commons#320
=> IBP-4822 browse study error when enviroments have the same location name

src/main/webapp/WEB-INF/pages/TrialManager/templates/subobservations/subObservationSet.html, src/main/webapp/WEB-INF/static/angular-templates/subObservations/observationInlineEditor.html, src/main/webapp/WEB-INF/static/js/trialmanager/subobservations/subObservationSet.js
BMETH_CODE scale's data type was changed from Character to Breeding Method. This PR fixes the rendering of breeding method dropdown in Observations accordingly
=> IBP-4979 Handle breeding method data type

src/main/java/com/efficio/fieldbook/web/trial/controller/OpenTrialController.java, src/main/java/com/efficio/fieldbook/web/util/FieldbookProperties.java, src/main/resources/Messages.properties, src/main/resources/fieldbook.properties, src/main/webapp/WEB-INF/Fieldbook-servlet.xml, src/main/webapp/WEB-INF/pages/TrialManager/createTrial.html, src/main/webapp/WEB-INF/static/angular-templates/instance-selector/multiple-instance-selector-modal.html, src/main/webapp/WEB-INF/static/angular-templates/instance-selector/multiple-instance-selector-modal.js, src/main/webapp/WEB-INF/static/js/trialmanager/manageTrial.js, src/main/webapp/WEB-INF/static/js/trialmanager/stabrapp/stabrapp-modal.html, src/main/webapp/WEB-INF/static/js/trialmanager/stabrapp/stabrapp-modal.js
- Off/hidden by default, enabled by Fieldbook property
- Launch in a separate window because of content security policy (we only allow now iframes from the same domain)
=> IBP-5226 STA BrAPP Launcher (Beta) in Manage Studies Actions

src/main/java/com/efficio/etl/service/impl/ETLServiceImpl.java, src/main/java/com/efficio/fieldbook/web/exception/DefaultExceptionHandler.java, src/main/java/com/efficio/fieldbook/web/exception/FieldbookRequestValidationException.java, src/main/resources/Messages.properties, src/main/webapp/WEB-INF/pages/etl/angular/angularOpenSheet.html, src/test/java/com/efficio/etl/service/ETLServiceTest.java
- Modify FieldbookRequestValidationException and Fieldbook
DefaultExceptionHandler to handle validation errors and params
- Handle ajax request errors in angularOpenSheet.html page
=> IBP-3716: Validate entry type in dataset importer

src/main/webapp/WEB-INF/static/js/fbk-data-table/fieldbook-datatable.js, src/main/webapp/WEB-INF/static/js/fieldbook-common.js, src/main/webapp/WEB-INF/static/js/trialmanager/germplasm/germplasm-details-modal/germplasm-details-module.js
=> IBP-4689 Germplasm details window is showing behind the import design window

src/main/webapp/WEB-INF/static/js/trialmanager/subobservations/subObservationSet.js
=> IBP-5306 reorder column problem

src/main/java/com/efficio/fieldbook/web/common/controller/GermplasmTreeController.java, src/test/java/com/efficio/fieldbook/web/common/controller/GermplasmTreeControllerTest.java
=> Fixing list creation

src/main/webapp/WEB-INF/pages/TrialManager/createTrial.html, src/main/webapp/WEB-INF/static/js/angular-tests/trialmanager/subObservationSet.spec.js, src/main/webapp/WEB-INF/static/js/trialmanager/datasetService.js, src/main/webapp/WEB-INF/static/js/trialmanager/germplasm-study-source/germplasmStudySource.js, src/main/webapp/WEB-INF/static/js/trialmanager/inventory/inventory-tab.js, src/main/webapp/WEB-INF/static/js/trialmanager/inventory/lot-creation/lot-creation-modal.js, src/main/webapp/WEB-INF/static/js/trialmanager/manageTrial.js, src/main/webapp/WEB-INF/static/js/trialmanager/subobservations/subObservationSet.js
Please, Review
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1220
https://github.com/IntegratedBreedingPlatform/Workbench/pull/656
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/660
=> IBP-5394 create lots from planted observation units

src/main/java/com/efficio/fieldbook/web/AbstractBaseFieldbookController.java, src/main/java/com/efficio/fieldbook/web/common/controller/ReviewStudyDetailsController.java, src/main/java/com/efficio/fieldbook/web/trial/controller/CreateTrialController.java, src/main/java/com/efficio/fieldbook/web/trial/controller/OpenTrialController.java, src/test/java/com/efficio/fieldbook/web/trial/controller/OpenTrialControllerTest.java
…book's environment dataset since they are not stored in separate dataset
IBP-5531 / IBP-5547
=> IBP-5531 - IBP-5531 Refactor Saving Of Summary Statistics

src/main/webapp/WEB-INF/static/js/trialmanager/subobservations/subObservationSet.js
=> IBP-5529-the-user-can-move-the-check-entries-and-file-column-in-observations-and-sub-observations

src/main/webapp/WEB-INF/static/js/trialmanager/inventory/planting-preparation/planting-preparation-modal.html, src/main/webapp/WEB-INF/static/js/trialmanager/inventory/planting-preparation/planting-preparation-modal.js
Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1271
=> IBP-5551-prepare_planting_inventory

src/main/java/com/efficio/etl/service/impl/ETLServiceImpl.java, src/main/java/com/efficio/fieldbook/web/common/controller/CrossingSettingsController.java, src/main/webapp/WEB-INF/Fieldbook-servlet.xml, src/test/java/com/efficio/etl/service/ETLServiceTestConfiguration.java, src/test/java/com/efficio/fieldbook/web/common/controller/CrossingSettingsControllerTest.java
=> IBP-5736-create-tool-service

src/main/java/com/efficio/etl/service/impl/ETLServiceImpl.java, src/main/resources/Messages.properties, src/test/java/com/efficio/etl/service/ETLServiceTest.java
Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Middleware/pull/1300
=> IBP-5739-Dataset_importer_add_entry_type_as_default

src/main/webapp/WEB-INF/pages/TrialManager/createTrial.html
=> IBP-5865-can_not_add_environment_conditional_variables

src/main/resources/Messages.properties, src/main/webapp/WEB-INF/static/angular-templates/location/locationSelect.html, src/main/webapp/WEB-INF/static/js/trialmanager/location/locationService.js
Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Workbench/pull/740
=> IBP-5825-location_selector_component_issues

src/main/java/com/efficio/fieldbook/web/importdesign/controller/DesignImportController.java, src/main/java/com/efficio/fieldbook/web/importdesign/service/DesignImportService.java, src/main/java/com/efficio/fieldbook/web/importdesign/service/impl/DesignImportServiceImpl.java, src/main/java/com/efficio/fieldbook/web/util/WorkbookUtil.java, src/test/java/com/efficio/fieldbook/web/importdesign/controller/DesignImportControllerTest.java, src/test/java/com/efficio/fieldbook/web/importdesign/service/impl/DesignImportServiceImplTest.java
=> IBP-5813-cannot-do-ssa-using-own-design-trial-instance-not-loading-on-page

src/main/webapp/WEB-INF/pages/Common/includes/crossingImportPresets.html, src/main/webapp/WEB-INF/pages/TrialManager/templates/crossingBreedingMethodModal.html, src/main/webapp/WEB-INF/static/angular-templates/advance/advanceStudyModal.html
Please, review
Included:
https://github.com/IntegratedBreedingPlatform/Commons/pull/360
https://github.com/IntegratedBreedingPlatform/Workbench/pull/748
=> IBP-5898_update_manual_links_for_v22

src/main/webapp/WEB-INF/static/js/trialmanager/germplasm/germplasm.js, src/main/webapp/WEB-INF/static/js/trialmanager/subobservations/subObservationSet.js
=> IBP-6065_error_sorting_columns_on_germplasm_and_check_tab

src/main/webapp/WEB-INF/static/js/trialmanager/environments.js
- prevent sending null as value to update instance descriptor API
=> IBP-5995: fix updating descriptor value for environment tab

src/main/java/com/efficio/etl/web/ImportObservationsController.java
Please, verify
Included:
https://github.com/IntegratedBreedingPlatform/BMSAPI/pull/790
=> IBP-5374 Duplicate rank when adding multiple traits to the study via import study book

src/main/webapp/WEB-INF/static/js/trialmanager/germplasm/breeding-method-modal/breeding-method-modal.js, src/main/webapp/WEB-INF/static/js/trialmanager/germplasm/germplasm-details-modal/germplasm-details-module.js, src/main/webapp/WEB-INF/static/js/trialmanager/manageTrial.js
**commit ab9951d9a327eac6559216b72b56847ce18df997 should not be included in a patch** for v23, as it affect the new browse studies code
=> IBP-6228, IBP-6193 PATCH: Use controller/jhipster (no absolute redirect)

src/main/webapp/WEB-INF/static/js/trialmanager/exportStudy.js
=> IBP-6251-ExportDataset

src/main/java/com/efficio/fieldbook/web/importdesign/validator/DesignImportValidator.java
=> IBP-6346 replace use StringUtils from mysql library

src/main/java/com/efficio/fieldbook/web/trial/controller/OpenTrialController.java, src/main/webapp/WEB-INF/pages/TrialManager/createTrial.html, src/main/webapp/WEB-INF/static/js/trialmanager/manageTrial.js, src/test/java/com/efficio/fieldbook/web/trial/controller/OpenTrialControllerTest.java
-  hide BrAPI study actions for users with program roles only
=> IBP-6340: add permissions for brapi calls

src/main/resources/Messages.properties, src/main/webapp/WEB-INF/pages/Common/includes/globals.html, src/main/webapp/WEB-INF/pages/TrialManager/templates/germplasmDetails.html, src/main/webapp/WEB-INF/static/js/trialmanager/germplasm/germplasm.js
=> IBP-6306-AddWarningForAddNewEntries

src/main/webapp/WEB-INF/pages/TrialManager/createTrial.html, src/main/webapp/WEB-INF/static/js/trialmanager/inventory/details/inventory-details-modal.js, src/main/webapp/WEB-INF/static/js/trialmanager/inventory/inventory-tab.html, src/main/webapp/WEB-INF/static/js/trialmanager/inventory/inventory-tab.js, src/main/webapp/WEB-INF/static/js/trialmanager/inventory/transaction-details/transaction-details-modal.html, src/main/webapp/WEB-INF/static/js/trialmanager/inventory/transaction-details/transaction-details-modal.js, src/main/webapp/WEB-INF/static/js/trialmanager/manageTrial.js
- add link for stock id to show lot transactions
- remove unnecessary transaction types
=> IBP-4511: improvements for studies inventory tab
